version: "3"
services:
  apache:
    image: httpd:alpine
    volumes:
      - ./public:/usr/local/apache2/htdocs/
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./.env:/usr/local/apache2/.env
      - ./storage:/usr/local/apache2/storage/
    environment:
      - FASTCGI=fcgi://phpfpm:9000
    hostname: "${HOSTNAME}"
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.5"
  phpfpm:
    build:
      context: .
      dockerfile: "./docker/php${PHP}"
    extra_hosts:
      - "${HOSTNAME}:${IPADDRESS}.5"
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
      - ./public:/usr/local/apache2/htdocs/
      - ./public:/usr/local/apache2/public/
      - ./vendor:/usr/local/apache2/vendor/
      - ./config:/usr/local/apache2/config/
      - ./storage:/usr/local/apache2/storage/
      - ./bootstrap:/usr/local/apache2/bootstrap/
      - ./app:/usr/local/apache2/app/
      - ./database:/usr/local/apache2/database/
      - ./resources:/usr/local/apache2/resources/
      - ./routes:/usr/local/apache2/routes/
      - ./.env:/usr/local/apache2/.env
      - ./composer.json:/usr/local/apache2/composer.json
      - ./artisan:/usr/local/apache2/artisan
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.6"
  db:
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.7"

networks:
  static-network:
    ipam:
      config:
        - subnet: "${IPADDRESS}.0/28"
